apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret # Nama Secret untuk menyimpan data sensitif
type: Opaque
data:
  # Password dalam format base64 (admin -> YWRtaW4=)
  mongo-root-username: YWRtaW4=
  mongo-root-password: c3VwZXJzZWNyZXRwYXNzd29yZA==