apiVersion: v1
kind: Service
metadata:
  name: mongo-service # Nama service agar bisa dipanggil oleh backend
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017 # Port service
      targetPort: 27017 # Port container