version: '3.8'

services:
  # 1. RabbitMQ Server
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"   # Port untuk koneksi aplikasi
      - "15672:15672" # Port untuk Dashboard Management (cek di browser)
    networks:
      - ecommerce-network

  # 2. Order Service
  order-service:
    image: ikbalbbm120/order-service:latest # GANTI DENGAN IMAGE DOCKER HUB KAMU
    container_name: order-service-container
    ports:
      - "4000:3000" # Sesuaikan port aplikasi kamu
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - ecommerce-network

  # 3. Shipping Service
  shipping-service:
    image: ikbalbbm120/shipping-service:latest # GANTI DENGAN IMAGE DOCKER HUB KAMU
    container_name: shipping-service-container
    ports:
      - "3001:3001" # Sesuaikan port aplikasi kamu
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge