apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-backend
  template:
    metadata:
      labels:
        app: karsajobs-backend
    spec:
      containers:
      - name: karsajobs-backend
        # Menggunakan image dari GitHub Packages (GHCR) sesuai saran reviewer
        image: ghcr.io/ikbalbbm120/karsajobs:latest 
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGODB_URL