apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
spec:
  type: NodePort # Tambahkan ini agar bisa diakses dari luar cluster
  selector:
    app: karsajobs-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 192.168.49.2 # Port yang akan digunakan di .env