apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
spec:
  type: NodePort # NodePort agar frontend bisa diakses dari browser melalui Minikube
  selector:
    app: karsajobs-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001 # Port akses manual di localhost