apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-backend
  template:
    metadata:
      labels:
        app: karsajobs-backend
    spec:
      containers:
      - name: karsajobs-backend
        # Menggunakan image dari GitHub Packages (GHCR) sesuai saran reviewer
        image: ghcr.io/ikbalbbm120/karsajobs:latest 
        ports:
        - containerPort: 8080
        env:
# 1. Tambahkan APP_PORT (Wajib!)
        - name: APP_PORT
          value: "8080"
          
        # 2. MONGODB_URL SUDAH DIHAPUS (Sesuai instruksi reviewer)

        # 3. Tetap gunakan variabel mongo yang sudah kamu buat
        - name: MONGO_HOST
          value: "mongo-service" 
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username 
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password