apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc # Klaim penyimpanan agar data database tidak hilang saat pod restart
spec:
  accessModes:
    - ReadWriteOnce # Bisa dibaca/tulis oleh satu node
  resources:
    requests:
      storage: 1Gi # Ukuran penyimpanan yang diminta